### ISSUE TITLE
Impossible to set label connectors for complex styles 

### ISSUE THREAD

**Issue by haubourg** [Oslandia/labelconnector#1]
I get this if source layers have ruled based styles, categorized or any complex renderer

![image](https://user-images.githubusercontent.com/1629853/57940662-42736b80-78cd-11e9-92d3-2b8306eb36d7.png)

**Comment by haubourg** [comment]
I see `2019-05-17T18:23:13     WARNING    QDialog::exec: Recursive call detected` into the Qt log panel

**Comment by haubourg** [comment]
On some layers (line), It just fails with no messages

**Comment by lbartoletti** [comment]
> Impossible d'ajouter le nouveau style 'label_style'

Fixed with  your commit for https://github.com/Oslandia/labelconnector/issues/5 :wink: 

I will check for line and symbology with rules

Thanks

**Comment by haubourg** [comment]
testing all renderers here : 

for lines and polygons: 

- Still not working with a ruled based renderer : 

![image](https://user-images.githubusercontent.com/1629853/58459559-f7a6ee80-812b-11e9-9196-3f24925e44b6.png)

- Works for categorised renderer 

- Doesn't work with Inverted polygon, it says it worked but when moving label, I have `Cannot apply LabelConnector to current style`, whatever the sub renderer is. I would maybe raise a message to advertise label connectors are not working with inverted polygon render. It make not much sense to me to label inverted polygons and is complicated because it has sub renderers.. (nested logic)

- 2.5 D renderer is not working with `Cannot apply LabelConnector to current style` when trying to move label. It works back when converting it back to simple style. Since 2.5 D renderer does not expose geometry generators, I would prevenderer, we should prevent creating connectors in that case. 
t users from being able to create connectors in that case too

- Same for 'no symbol' renderer, we should prevent creating connectors in that case. 

- for points displacement point renderer, same thing, this makes no sense. 

- For point clusters, and heatmap, same thing, let's disable label connector 

In the end, this points a lot of caveats that show the necessity of having connectors part of the labeling classes and in core :)

**Comment by lbartoletti** [comment]
Fixed for Inverted polygon, 2.5 D renderer, 'no symbol', points displacement, point clusters and heatmap in https://github.com/Oslandia/labelconnector/commit/c7522b5f0c455965d3e3e67474506562811942c8
 My bad, I forgot the return. I added another verification....

> In the end, this points a lot of caveats that show the necessity of having connectors part of the labeling classes and in core :)

Oh yes!

For "simple" rule based it works, but you have sub rule, so I have to check all cases :)

**Comment by lbartoletti** [comment]
Fixed for rule render https://github.com/Oslandia/labelconnector/commit/b6c7edf64214ae695aae201d156413a1132facb7
